import { Toaster } from '@repo/ui/components/sonner';
import { TooltipProvider } from '@repo/ui/components/tooltip';
import { ThemeProvider } from '@repo/ui/contexts/NextThemesProvider';
import '@repo/ui/globals.css';
import { cn } from '@repo/ui/lib/utils';
import 'cropperjs/dist/cropper.css';
import type { Metadata } from 'next';
import { Inter, Merriweather, Poppins, Roboto } from 'next/font/google';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

const roboto = Roboto({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

const merriweather = Merriweather({
  weight: ['300', '400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-merriweather',
});

export const metadata: Metadata = {
  title: 'Munza',
  description: 'Generated by Munza',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'antialiased text-base',
          inter.className,
          roboto.variable,
          poppins.variable,
          merriweather.variable,
        )}
      >
        <ThemeProvider>
          <TooltipProvider>
            <StoreProvider>{children}</StoreProvider>
          </TooltipProvider>
          <Toaster position="bottom-right" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
